trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python src/data_ingestion.py
    displayName: 'Run Data Ingestion'

  - script: |
      python src/data_preprocessing.py
    displayName: 'Run Data Preprocessing'

  - script: |
      python src/feature_engineering.py
    displayName: 'Run Feature Engineering'

  - script: |
      python src/feature_selection.py
    displayName: 'Run Feature Selection'

  - script: |
      python src/train_model.py
    displayName: 'Train Model'

  - script: | 
    python src/deploy_model_aci.py
    displayName: 'Deploy Model to ACI' 
    
  - script: |
  python src/deploy_model_aks.py 
  displayName: 'Deploy Model to AKS'

  - script: |
    python src/register_model.py
    displayName: 'Register Model'
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)'
      artifactName: 'models'
